modLoader="kotlinfml"
loaderVersion="[1,)"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="test-mod"
version="${file.jarVersion}"
displayName="Test Mod"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
logoFile="examplemod.png"
credits=""
authors="Alex"
description='''
'''

[[dependencies.test-mod]]
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.test-mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"